# Generated by Django 4.2.1 on 2023-06-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_listing_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TOY", "Toys"),
                    ("ELC", "Electronics"),
                    ("HOM", "Home"),
                    ("TOO", "Tools"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
