# Generated by Django 4.2.1 on 2023-06-04 21:56

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_listing_category_alter_listing_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[auctions.models.validate_price],
            ),
        ),
    ]
