# Generated by Django 4.2.1 on 2023-06-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_listing_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_active",
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
