# Generated by Django 4.2.1 on 2023-06-08 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_listing_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchers",
            field=models.ManyToManyField(
                auto_created=True,
                blank=True,
                default=None,
                related_name="watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
